	WOW_PROJECT_MAINLINE = 1
	WOW_PROJECT_CLASSIC = 2
	WOW_PROJECT_BURNING_CRUSADE_CLASSIC = 5
	WOW_PROJECT_WRATH_CLASSIC = 11
WOW_PROJECT_ID = WOW_PROJECT_WRATH_CLASSIC

	LE_EXPANSION_CLASSIC = 0
	LE_EXPANSION_BURNING_CRUSADE = 1
	LE_EXPANSION_WRATH_OF_THE_LICH_KING = 2
	LE_EXPANSION_CATACLYSM = 3
	LE_EXPANSION_MISTS_OF_PANDARIA = 4
	LE_EXPANSION_WARLORDS_OF_DRAENOR = 5
	LE_EXPANSION_LEGION = 6
	LE_EXPANSION_BATTLE_FOR_AZEROTH = 7
	LE_EXPANSION_SHADOWLANDS = 8
	LE_EXPANSION_DRAGONFLIGHT = 9
	LE_EXPANSION_11_0 = 10
LE_EXPANSION_LEVEL_CURRENT = LE_EXPANSION_WRATH_OF_THE_LICH_KING

AURA_TYPE_DEBUFF = "DEBUFF"
AURA_TYPE_BUFF = "BUFF"

RAID_CLASS_COLORS.HUNTER.colorStr = "ffabd473"
RAID_CLASS_COLORS.WARLOCK.colorStr = "ff8788ee"
RAID_CLASS_COLORS.PRIEST.colorStr = "ffffffff"
RAID_CLASS_COLORS.PALADIN.colorStr = "fff58cba"
RAID_CLASS_COLORS.MAGE.colorStr = "ff3fc7eb"
RAID_CLASS_COLORS.ROGUE.colorStr = "fffff569"
RAID_CLASS_COLORS.DRUID.colorStr = "ffff7d0a"
RAID_CLASS_COLORS.SHAMAN.colorStr = "ff0070de"
RAID_CLASS_COLORS.WARRIOR.colorStr = "ffc79c6e"
RAID_CLASS_COLORS.DEATHKNIGHT.colorStr = "ffc41f3b"

INLINE_TANK_ICON = "|TInterface\\LFGFrame\\UI-LFG-ICON-PORTRAITROLES.blp:16:16:0:0:64:64:0:19:22:41|t";
INLINE_HEALER_ICON = "|TInterface\\LFGFrame\\UI-LFG-ICON-PORTRAITROLES.blp:16:16:0:0:64:64:20:39:1:20|t";
INLINE_DAMAGER_ICON = "|TInterface\\LFGFrame\\UI-LFG-ICON-PORTRAITROLES.blp:16:16:0:0:64:64:20:39:22:41|t"

SPECIALIZATION = "Spec"

COMPACT_UNIT_FRAME_COUNTDOWN_START = "Pull in %s"
COMPACT_UNIT_FRAME_COUNTDOWN_NOW = "Pull Now!"